### ISSUE TITLE
Odoo 15 support?

### ISSUE THREAD

**Issue by poVoq** [abdulah-khaleel/bid-evaluation-app#1]
This looks useful :)

Any plans for Odoo 15 support?

**Comment by abdulah-khaleel** [comment]
Thanks. Yes, will also work on v15 right after I finish up one major remaining functionality - probably towards end of the week. Will post here once done.

**Comment by abdulah-khaleel** [comment]
Thanks. Yes, will also work on v15 right after I finish up one major remaining functionality - probably towards end of the week. Will post here once done.

**Comment by abdulah-khaleel** [comment]
@poVoq sorry took a while - just released v15 as well in case you haven't been using the older commits already. See branch 15.0.

**Comment by abdulah-khaleel** [comment]
https://apps.odoo.com/apps/modules/15.0/ak_bid_evaluation/

**Comment by poVoq** [comment]
Seems to work fine from a quick test on my Odoo 15 CE. Thanks for making this, looks really useful!

**Comment by abdulah-khaleel** [comment]
Great and thank you - hope the app proves helpful.
